languageCode = "en-us"
title = "exceleron.design"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"
enableEmoji = true

[params]
  description = "Documentation for common design and code patterns used by Exceleron Designs."
