languageCode = "en-us"
title = "exceleron.design"
baseURL = "https://excelerondesign.github.io/cupper"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Documentation for common design and code patterns used by Exceleron Designs."
