[build]
    HUGO_VERSION = "0.86.1"
[context.deploy-preview]
    baseUrl = "$DEPLOY_PRIME_URL"
[context.branch-deploy]
    baseUrl = "$DEPLOY_PRIME_URL"
[context.production]
    baseUrl = "$DEPLOY_PRIME_URL"