[build]
    HUGO_VERSION = "0.86.1"
    command = "rm -rfv ./docs && hugo -b $URL && sw-precache --root=docs"
[context.deploy-preview]
    command = "rm -rfv ./docs && hugo -b $DEPLOY_URL && sw-precache --root=docs"
[context.branch-deploy]
    command = "rm -rfv ./docs && hugo -b $DEPLOY_PRIME_URL && sw-precache --root=docs"
[context.production]
    command = "rm -rfv ./docs && hugo -b $DEPLOY_PRIME_URL && sw-precache --root=docs"