[build]
    HUGO_VERSION = "0.86.1"
[context.deploy-preview]
    HUGO_BASE_URL = "$DEPLOY_PRIME_URL"
[context.branch-deploy]
    HUGO_BASE_URL = "$DEPLOY_PRIME_URL"
[context.production]
    command = "rm -rfv ./docs && hugo -b $DEPLOY_PRIME_URL && sw-precache --root=docs"