[build]
    HUGO_VERSION = "0.86.1"
    baseUrl = "$DEPLOY_PRIME_URL"
[context.deploy-preview]
[context.branch-deploy]
[context.production]
    command = "rm -rfv ./docs && hugo && sw-precache --root=docs"