[build]
    HUGO_VERSION = "0.86.1"
[context.deploy-preview]
    HUGO_BASE_URL = "$DEPLOY_PRIME_URL"
[context.branch-deploy]
    HUGO_BASE_URL = "$DEPLOY_PRIME_URL"
[context.production]
    HUGO_BASE_URL = "$DEPLOY_PRIME_URL"